version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: wordpress
      POSTGRES_PASSWORD: wordpress
      POSTGRES_DB: wordpress
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  wordpress:
    build: ./wp
    container_name: my_wordpress
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:5432
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db_data:
